Repository AndrewRedican/react-json-editor-ajrm, pull requests merged in 2018-08, with the labels that each got.

#35 Core tests
  .gitignore
  CHANGELOG.md
  README.md
  example/package.json
  example/src/sampledata.js
  package-lock.json
  package.json
  src/index.js
  test/__snapshots__/test.js.snap
  test/err.js
  test/jest.transform.js
  test/logic/index.js
  test/logic/locale.js
  test/logic/syntax.js
  test/logic/testSyntaxLogic.js
  test/render/index.js
  test/sampleData.js
  test/test.js
Labels: bug fixes, enhancement, tests

#41 Added support to pt
  .all-contributorsrc
  CHANGELOG.md
  README.md
  src/locale/pt.js
Labels: translation

#43 Make the "Tab" key no longer change focus
  src/index.js
Labels: bug fixes

#52 Example/plain create react app example
  .all-contributorsrc
  README.md
  example/babel.config.js
  example/create-react-app-project/.gitignore
  example/create-react-app-project/README.md
  example/create-react-app-project/package.json
  example/create-react-app-project/public/favicon.ico
  example/create-react-app-project/public/index.html
  example/create-react-app-project/public/manifest.json
  example/create-react-app-project/src/index.css
  example/create-react-app-project/src/index.js
  example/create-react-app-project/src/logo.svg
  example/create-react-app-project/src/registerServiceWorker.js
  example/create-react-app-project/src/sampledata.js
  example/create-react-app-project/yarn.lock
  example/src/index.js
  example/webpack-project/.gitignore
  example/webpack-project/babel.config.js
  example/webpack-project/package-lock.json
  example/webpack-project/package.json
  example/webpack-project/src/index.css
  example/webpack-project/src/index.html
  example/webpack-project/src/index.js
  example/webpack-project/src/sampledata.js
  example/webpack-project/webpack.config.js
Labels: enhancement, reviewing code
